repos:
    - repo: https://github.com/python-poetry/poetry
      rev: 1.6.1
      hooks:
        - id: poetry-export
          args: ["-f", "requirements.txt", "-o", "requirements.txt"]
          verbose: true
