repos:
    # - repo: https://github.com/python-poetry/poetry
    #   rev: 2.1.3
    #   hooks:
    #     - id: poetry-export
    #       args: ["-f", "requirements.txt", "-o", "requirements.txt"]
    #       verbose: true

    - repo: local
      hooks:
        - id: poetry-requirements-export
          name: Poetry requirements export
          entry: bash -c "poetry export -f requirements.txt -o requirements.txt"
          language: system
    

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.12.0
      hooks:
        - id: ruff
        - id: ruff-format