repos:
    # - repo: https://github.com/python-poetry/poetry
    #   rev: 2.1.3
    #   hooks:
    #     - id: poetry-export
    #       args: ["-f", "requirements.txt", "-o", "requirements.txt"]
    #       verbose: true

    - repo: https://github.com/astral-sh/uv-pre-commit
      rev: 0.8.0
      hooks:
        - id: uv-export

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.12.0
      hooks:
        - id: ruff
        - id: ruff-format