[tool.poetry]
name = "smolagent-tuto"
version = "0.1.0"
description = "Agent tutorial"
authors = ["Adrien <ruaultadrien@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
smolagents = "^1.17.0"
duckduckgo-search = "^8.0.2"
gradio = "^5.31.0"
opentelemetry-sdk = "^1.33.1"
opentelemetry-exporter-otlp = "^1.33.1"
openinference-instrumentation-smolagents = "^0.1.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
